# Site
repository: Hyunjoon526/hyunjoon526.github.io
favicon: images/favicon.ico

# Personal info
name: Hyunjoon Kim
title: Assistant Professor
#email: hjkim@theory.snu.ac.kr
email: hyunjoonkim@hanyang.ac.kr
website: hyunjoon526.github.io
lab: sites.google.com/view/hyudatalab 

# Social links
#twitter_username: facespics
github_username:  hyunjoon526
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: hyunjoon-kim
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
googlescholar_username: yrPlV5kAAAAJ&hl=en
cv_username: hjkimCV

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Hyunjoon Kim. I serve as an assistant professor in Department of Data Science at Hanyang University. I received B.S. in Computer Science and Engineering from Seoul National University. In 2020, I received Ph.D. in Computer Science and Engineering at Seoul National University. In 2020-2021, I had worked as a senior developer at SAP Labs Korea.
  My research interests are <mark>Big Data Analysis</mark>, <mark>Data Mining</mark>, and <mark>Artificial Intelligence</mark>. At Hanyang University, I lead the [Information Retrieval and Data Mining Lab.](https://sites.google.com/view/hyudatalab).
 
# Education Section
educaton_title: Education

# Experience Section
experience_title: Work Experience

# Publications Section
publications_title: Selected Publications

# Projects Section
#projects_title: Projects

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: Hyunjoon526/hyunjoon526.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Show future posts
future: true
# Specify my timezone
timezone: TIMEZONE

theme: jekyll-theme-minimal
