# Site
repository: Hyunjoon526/hyunjoon526.github.io
favicon: images/favicon.ico

# Personal info
name: Hyunjoon Kim
title: Ph.D. student
#email: hjkim@theory.snu.ac.kr
email: hyunjoonkim@hanyang.ac.kr
website: hyunjoon526.github.io

# Social links
#twitter_username: facespics
github_username:  hyunjoon526
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: hyunjoon-kim
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
googlescholar_username: yrPlV5kAAAAJ&hl=en
cv_username: hjkimCV

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Currently Hyunjoon Kim serves as an assistant professor in Department of Data Science at Hanyang University, Seoul, Korea. 
  He graduated from Seoul National University in computer science and engineering. In 2020, he completed PhD degree in computer science and engineering at Seoul National University. In 2020-2021, he had worked as a software developer at SAP Labs Korea.
  His research interests are <mark>Big Data Analysis</mark>, <mark>Graph Database</mark>, <mark>Information Retrieval</mark>, <mark>Graph Neural Networks</mark>, <mark>Algorithms & Data Structures</mark>
 
# Education Section
educaton_title: Education

# Experience Section
experience_title: Work Experience

# Publications Section
publications_title: Selected Publications

# Projects Section
#projects_title: Projects

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: Hyunjoon526/hyunjoon526.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Show future posts
future: true
# Specify my timezone
timezone: TIMEZONE

theme: jekyll-theme-minimal
