# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Hyunjoon Kim
title: Ph.D. Candidate
email: hjkim@theory.snu.ac.kr
website: hyunjoon526.github.io

# Social links
#twitter_username: facespics
github_username:  hyunjoon526
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: hyunjoon-kim
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hyunjoon Kim and I'm a Ph.D. candidate in computer science and engineering, Seoul National University.
  My research interests are <mark>Big Data Analysis</mark>, <mark>Graph Database</mark>, <mark>Algorithms & Data Structures</mark>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Show future posts
future: true
# Specify my timezone
timezone: TIMEZONE
